# meta data
log_level: INFO

# ベクトルストア作成
separators: 
  - "\n\n"
  - "。"
  - "、"
  - "\n"
chunk_size: 1000
chunk_overlap: 200


# 推論
model_provider: anthropic
model_name: claude-3-5-sonnet-20240620
temperature: 0
max_tokens: 50
max_workers: 3

# RAG
top_k: 2
is_ordinal: false
